name: Jacoco Code Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11.0
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots test jacoco:report

      - name: Coveralls GitHub Action        
        uses: coverallsapp/github-action@v2.3.0

      - name: Coveralls Coverage Report Submission
        env:
           github-token: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B coveralls:report
       

